dtype: bfloat16
flux_path: black-forest-labs/FLUX.1-dev
model:
  add_cond_attn: false
  latent_lora: false
  union_cond_attn: true
train:
  accumulate_grad_batches: 1
  batch_size: 1
  condition_type: tryon
  dataloader_workers: 5
  dataset:
    condition_size: 512
    data_list: train_pairs.txt
    drop_image_prob: 0.0
    drop_text_prob: 0.1
    root: /workspace1/pdawson/tryon-scraping/dataset2
    target_aspect_ratio: 1.5
    target_size: 512
    type: tryon
  gradient_checkpointing: true
  lora_config:
    init_lora_weights: gaussian
    lora_alpha: 4
    r: 4
    target_modules: (.*x_embedder|.*(?<!single_)transformer_blocks\.[0-9]+\.norm1\.linear|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_k|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_q|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_v|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_out\.0|.*(?<!single_)transformer_blocks\.[0-9]+\.ff\.net\.2|.*single_transformer_blocks\.[0-9]+\.norm\.linear|.*single_transformer_blocks\.[0-9]+\.proj_mlp|.*single_transformer_blocks\.[0-9]+\.proj_out|.*single_transformer_blocks\.[0-9]+\.attn.to_k|.*single_transformer_blocks\.[0-9]+\.attn.to_q|.*single_transformer_blocks\.[0-9]+\.attn.to_v|.*single_transformer_blocks\.[0-9]+\.attn.to_out)
  max_steps: -1
  optimizer:
    params:
      lr: 1
      safeguard_warmup: true
      use_bias_correction: true
      weight_decay: 0.01
    type: Prodigy
  sample_interval: 100
  save_interval: 1000
  save_path: runs
  wandb:
    project: OminiControl - Tryon
